server:
  port: 8080

#person:
##    name: 张三
#    age: 19
#    boss: false
#    maps:
#        k1: v1
#        k2: 19
#    list:
#        - 111
#        - 222
#    dog:
#        name: 旺财
#        age: 1
#    name: aaa
